### ISSUE TITLE
500 blank page on Ubuntu 20.04

### ISSUE THREAD

**Issue by Pluxx** [raaaimund/typo3-docker#1]
Hi Raimund,

i know this script is quite "outdated" but it should still be able to run. 

I tried this on Ubuntu 18 and Ubuntu 20 and both show me nginx 500 blank pages with the TYPO3 installer (9 or 10). I was able to install Wordpress tho on the public folder, which is super weird, but TYPO3 does nothing.

Any idea what could be wrong? Or is this docker script only tested on Mac?

**Comment by raaaimund** [comment]
You are totally right, I will take a look in the coming days.

**Comment by raaaimund** [comment]
I am working on Win10, but I can probably check it with WSL2 and Ubuntu. It seems there are some permission errors, maybe because I used `composer:latest`, but let's see.

**Comment by raaaimund** [comment]
I use a volume now instead of mounting a local folder from the host to the containers. I also tested it with Ubuntu 18.04 and it worked (using WSL 2).
